version: '3'
services:
  db:
    image: postgres
    platform: linux/amd64
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'

  web:
    build:
      context: .
      dockerfile: "Dockerfile.prod"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - '3000:3000'
    depends_on:
      - db
volumes:
  postgresql-data:
    driver: local