# fly.toml app configuration file generated for one-minute-talk on 2024-02-15T20:21:15+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#
# hostnameになる？1mintalk.comにかえる？
app = 'one-minute-talk'
primary_region = 'nrt'
console_command = '/rails/bin/rails console'

[processes]
  web = "bin/rails server"
  cron = "supercronic /rails/crontab"

[build]

[deploy]
  release_command = './bin/rails db:prepare'

[http_service]
  internal_port = 3000 # 8080にする?
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['web']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512 # 1024に変更する?

[[statics]]
  guest_path = '/rails/public'
  url_prefix = '/'
